### ISSUE TITLE
SerializeLinqExpressionSerializer.cs - no matching element

### ISSUE THREAD

**Issue by ionican** [Tewr/BlazorWorker#72]
Using the latest release I'm getting an error when attempting to instantiate the worker through RunAsync: 
```
var service = await worker.CreateBackgroundServiceAsync<DataLoader>(
                              options => options
                              .AddAssemblies("IMS36.dll", "IMS36.Shared.dll", "System.Net.Http.dll", "System.Net.Primitives.dll", "System.Security.Cryptography.X509Certificates.dll",
                              "System.Diagnostics.Tracing.dll", "Microsoft.Extensions.DependencyInjection.dll").AddHttpClient()
                          );
```
`var result = await service.RunAsync(s => s.UpdateAllTablesAsync(_state,""));`

Console:
```
3e8d9e9d-515f-4de4-b444-0c9b87f230c8:66 WASM-WORKER: BlazorWorker.WorkerBackgroundService.WorkerInstanceManager.PostMessage(): {"MessageType":"InitWorkerComplete"}.
13:08:18.110 3e8d9e9d-515f-4de4-b444-0c9b87f230c8:66 WASM-WORKER: BlazorWorker.WorkerBackgroundService.WorkerInstanceManager.Init(): Done.
13:08:18.276 blazor.webassembly.js:1 WorkerBackgroundServiceProxy.InitAsync(): 1 {"WorkerId":1,"InstanceId":1,"AssemblyName":"IMS36, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","TypeName":"IMS36.DataLoader","CallId":1,"MessageType":"InitInstance"}
13:08:18.389 3e8d9e9d-515f-4de4-b444-0c9b87f230c8:66 WASM-WORKER: BlazorWorker.WorkerBackgroundService.WorkerInstanceManager.PostMessage(): {"CallId":1,"IsSuccess":true,"Exception":null,"MessageType":"InitInstanceComplete"}.
13:08:18.390 3e8d9e9d-515f-4de4-b444-0c9b87f230c8:66 WASM-WORKER: MessageService.OnMessage: {"WorkerId":1,"InstanceId":1,"AssemblyName":"IMS36, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","TypeName":"IMS36.DataLoader","CallId":1,"MessageType":"InitInstance"}
```

```
blazor.webassembly.js:1 
        
       crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Sequence contains no matching element
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[FieldInfo](IEnumerable`1 source, Func`2 predicate)
   at Serialize.Linq.Factories.TypeResolverNodeFactory.TryToInlineExpression(MemberExpression memberExpression, Expression& inlineExpression)
   at Serialize.Linq.Factories.TypeResolverNodeFactory.ResolveMemberExpression(MemberExpression memberExpression)
   at Serialize.Linq.Factories.TypeResolverNodeFactory.Create(Expression expression)
   at System.Linq.Enumerable.SelectIListIterator`2[[System.Linq.Expressions.Expression, System.Linq.Expressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[Serialize.Linq.Nodes.ExpressionNode, Serialize.Linq, Version=1.8.1.0, Culture=neutral, PublicKeyToken=25bcc11ba213b377]].MoveNext()
   at System.Collections.Generic.List`1[[Serialize.Linq.Nodes.ExpressionNode, Serialize.Linq, Version=1.8.1.0, Culture=neutral, PublicKeyToken=25bcc11ba213b377]].InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1[[Serialize.Linq.Nodes.ExpressionNode, Serialize.Linq, Version=1.8.1.0, Culture=neutral, PublicKeyToken=25bcc11ba213b377]].AddRange(IEnumerable`1 collection)
   at Serialize.Linq.Nodes.ExpressionNodeList..ctor(INodeFactory factory, IEnumerable`1 items)
   at Serialize.Linq.Nodes.MethodCallExpressionNode.Initialize(MethodCallExpression expression)
   at Serialize.Linq.Nodes.ExpressionNode`1[[System.Linq.Expressions.MethodCallExpression, System.Linq.Expressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]]..ctor(INodeFactory factory, MethodCallExpression expression)
   at Serialize.Linq.Nodes.MethodCallExpressionNode..ctor(INodeFactory factory, MethodCallExpression expression)
   at Serialize.Linq.Factories.NodeFactory.Create(Expression expression)
   at Serialize.Linq.Factories.TypeResolverNodeFactory.ResolveMethodCallExpression(MethodCallExpression methodCallExpression)
   at Serialize.Linq.Factories.TypeResolverNodeFactory.Create(Expression expression)
   at Serialize.Linq.Nodes.LambdaExpressionNode.Initialize(LambdaExpression expression)
   at Serialize.Linq.Nodes.ExpressionNode`1[[System.Linq.Expressions.LambdaExpression, System.Linq.Expressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]]..ctor(INodeFactory factory, LambdaExpression expression)
   at Serialize.Linq.Nodes.LambdaExpressionNode..ctor(INodeFactory factory, LambdaExpression expression)
   at Serialize.Linq.Factories.NodeFactory.Create(Expression expression)
   at Serialize.Linq.Factories.TypeResolverNodeFactory.Create(Expression expression)
   at Serialize.Linq.Factories.DefaultNodeFactory.Create(Expression expression)
   at Serialize.Linq.Serializers.ExpressionConverter.Convert(Expression expression, FactorySettings factorySettings)
   at Serialize.Linq.Serializers.ExpressionSerializer.SerializeText(Expression expression, FactorySettings factorySettings)
   at BlazorWorker.WorkerBackgroundService.SerializeLinqExpressionSerializer.Serialize(Expression expression) in C:\Users\microDevBox\source\repos\IMS36\BlazorWorker3.1.0\src\BlazorWorker.WorkerBackgroundService\SerializeLinqExpressionSerializer.cs:line 22
   at BlazorWorker.BackgroundServiceFactory.WorkerBackgroundServiceProxy`1.<InvokeAsyncInternal>d__45`1[[IMS36.DataLoader, IMS36, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[IMS36.Shared.Models.ManifestBox`1[[IMS36.StateContainer.State, IMS36, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], IMS36.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext() in C:\Users\microDevBox\source\repos\IMS36\BlazorWorker3.1.0\src\BlazorWorker.ServiceFactory\WorkerBackgroundServiceProxy.cs:line 379
   at BlazorWorker.BackgroundServiceFactory.WorkerBackgroundServiceProxy`1.<RunAsync>d__41`1[[IMS36.DataLoader, IMS36, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[IMS36.Shared.Models.ManifestBox`1[[IMS36.StateContainer.State, IMS36, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], IMS36.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext() in C:\Users\microDevBox\source\repos\IMS36\BlazorWorker3.1.0\src\BlazorWorker.ServiceFactory\WorkerBackgroundServiceProxy.cs:line 307
   at IMS36.StateDataManager.InitiateDataLoad(Int32 chunkSize, Int32 delay) in C:\Users\microDevBox\source\repos\IMS36\IMS36\State\StateDataManager.cs:line 55
   at IMS36.Shared.MainLayout.OnInitializedAsync() in C:\Users\microDevBox\source\repos\IMS36\IMS36\Shared\MainLayout.razor:line 168
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**Comment by ionican** [comment]
Hi - thanks for the rapid response.  State is a cache of my db held locally (6 tables presently) - the worker above issues requests to the API to populate it.  I guess I could totally flatten it by creating separate workers for each table... I'll try this and report back!

**Comment by ionican** [comment]
Right!  So this works!  I stripped the worker down to being a simple httpClient request:
```
       public async Task<ApiResponse<List<T>>> Worker<T>(string endPoint, int lastRecordId, int chunkSize)
        {
            return await _httpClient.GetFromJsonAsync<ApiResponse<List<T>>>($"{endPoint}/{lastRecordId}/{chunkSize}");
        }
```
called from my 'dataloader':

```
 public async Task<ApiResponse<List<T>>> WorkerGetData<T>(string endPoint,int lastRecordId,int chunkSize)
        {
            var worker = await _workerFactory.CreateAsync();
            var service = await worker.CreateBackgroundServiceAsync<WorkerDataLoader>(
                          options => options
                          .AddAssemblies("IMS36.dll", "IMS36.Shared.dll", "System.Net.Http.Json.dll" ,"System.Net.Http.dll", "System.Text.Encodings.Web.dll",
                          "System.Net.Primitives.dll", "System.Security.Cryptography.X509Certificates.dll", "System.Text.Json.dll",
                          "System.Diagnostics.Tracing.dll", "Microsoft.Extensions.DependencyInjection.dll")
                      );

            var fullURI = xbaseURLs.api + endPoint;
            var result = await service.RunAsync(s => s.Worker<T>(fullURI, lastRecordId, chunkSize));
            return result;
        }
```

The data 'fetch' (100,000 rows in this case) worked perfectly in the background, taking 5 seconds, the UI being fully usable... 

Thanks for your help on this - much appreciated.

**Comment by ionican** [comment]
Following on - I found a caveat to the above... the 'handover' of the data received from the Worker to the UI thread is taking longer than the httpClient routine itself.  I've put timers on the various parts of the 'WorkerGetData' method and also inside the worker:

```
Generating Worker Background Service
blazor.webassembly.js:1 Service created in 540ms
blazor.webassembly.js:1 Worker External: Beginning Manifest load
1a7688f1-31c9-4c65-846e-b6092e209560:66 WASM-WORKER: Worker internal: Beginning manifest load
1a7688f1-31c9-4c65-846e-b6092e209560:66 WASM-WORKER: Worker internal: Manifest load finished - in 241
blazor.webassembly.js:1 Worker External: Manifest load finished - in 561ms
dotnet.6.0.2-mauipre.1.22054.8.pfzxtngldm.js:1 [Violation] 'setTimeout' handler took 182ms
```

This is for a very small dataset (about 20 items, 470Bytes).  Is this to be expected?  The UI is feeling a bit 'jittery' as a result and on occasions locks solid during the worker->ui handover (when I load a larger dataset).

**Comment by ionican** [comment]
A larger dataset!:
```
Worker External: Beginning data load
719d0957-5849-4b23-ad4d-1ad481d63ffd:66 WASM-WORKER: Worker internal: Beginning data load
719d0957-5849-4b23-ad4d-1ad481d63ffd:66 WASM-WORKER: Worker internal: Data load finished - 10000 items in 1562
blazor.webassembly.js:1 Worker External: Data load finished - 10000 items in 12125ms
44f2405e-413f-40c4-9f5c-70be620d1a03:287 [Violation] 'message' handler took 8340ms
```

**Comment by Tewr** [comment]
The transfer of large messages is not something this library does very well. You have to serialize to string, pass it from wasm to js, pass to UI thread, pass the string back to wasm and then deserialize.

"pass to UI thread, pass the string back to wasm and then deserialize" is done on the UI thread.

You could implement streaming/chunking for this part by chunking up the result somehow. It will be less jittery, but smoother for the user, but it certainly won't be faster.

Lots of options on how to implement this, but the simplest one:

Expose events from your treatment. Declare an event on your service, the event listener being on the UI thread, getting back one item at a time. This is probably the easiest way of chunking back a result.
If you manage to use a streaming deserializer from your http call that would be the fastest way, as you can start treating items on the UI thread even before the worker has finished.

**Comment by ionican** [comment]
Many thanks for this - your chunking solution does sound like the most straightforward way of doing this (raw performance isn't probably so much of an issue as the data probably won't be needed immediately and if it is I can then block the UI with an appropriate 'loading' message and max-speed it).

**Comment by Tewr** [comment]
Closing due to inactivity
